- Readme.md
Just some small grammar fixes to make the readme a bit smoother. I also added in a link to submit new issues.
> Grammar fixes

- src/server/utils/versionStatus.ts
> remove TS version from status line

- Readme.md
See #37 . Relatively hard-to-find config value, common use case. Thanks for all your work on coc-tsserver! I'm finding it very useful.
> Expand JSX/TSX note to mention `typescriptreact`

- src/server/languageProvider.ts
close #77 
https://github.com/neoclide/coc-tsserver/blob/master/src/server/typescriptServiceClientHost.ts#L193
> fix(server): fix reportUnnecessary

- package.json
- yarn.lock
> Fix dependencies error while upgrade to Typescript 3.7

- Readme.md
As two words this would be something like trouble, shooting! as-in 😱 🔫 , haha.
> Make troubleshooting one word in readme

- Readme.md
Hello!
I clarified the installation instructions for nvm users and removed the previous nvm note.
> docs(readme): clarifying nvm instructions

- src/server/utils/completionItem.ts
https://github.com/microsoft/vscode/pull/104479
> Don't include this function types in completeFunctionCall

- src/server/typescriptServiceClient.ts
> fix up the locale

- package.json
- src/server/features/updatePathOnRename.ts
- src/server/utils/typingsStatus.ts
- yarn.lock
Hello,
I updated the typescript dependency to version 4.1.2 and then had to fix a few typings to be able to run `yarn build`.
Regards.
> update ts to 4.1.2 and fix build (promise typings)

- Readme.md
- package.json
- src/server/features/fileConfigurationManager.ts
https://github.com/microsoft/TypeScript/pull/41304
> feat: add insertSpaceAfterOpeningAndBeforeClosingEmptyBraces

- Readme.md
This is a typo correction for code block
> Fix code block in README

- src/server/utils/versionStatus.ts
> Nitpick: Spelling fix.

- Readme.md
- package.json
- src/server/features/completionItemProvider.ts
- src/server/features/fileConfigurationManager.ts
- src/server/utils/api.ts
- src/server/utils/completionItem.ts
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#import-statement-completions
https://user-images.githubusercontent.com/345274/119966615-13c11d00-bfde-11eb-9352-d64d5963734e.mov
> feat: Import Statement Completions

- package.json
- src/server/features/fileConfigurationManager.ts
https://github.com/microsoft/vscode/pull/110536
> feat: update preferences.importModuleSpecifier

- package.json
- src/server/features/watchBuild.ts
This adds support for a new "tsconfigPath" setting for tsserver.
> Add support for tsconfigPath setting

- package.json
- src/server/features/callHierarchy.ts
- src/server/languageProvider.ts
- src/server/protocol.const.ts
- src/server/typescriptService.ts
- src/server/utils/typeConverters.ts
- yarn.lock
needs https://github.com/neoclide/coc.nvim/pull/2756, `call CocAction('incomingCalls')`
closes https://github.com/neoclide/coc-tsserver/issues/128
> feat: callHierarchy support

- package.json
- src/server/commands.ts
- yarn.lock
I don't know it ok to use `this.service.id` as the collection name, in my tests it works.
> fix: getDiagnostics breaking changes

- src/server/features/semanticTokens.ts
- src/server/languageProvider.ts
- src/server/utils/api.ts
Ported from https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/semanticTokens.ts
needs https://github.com/neoclide/coc.nvim/pull/3357
> feat: add semanticTokens support

- Readme.md
- package.json
- src/server/features/fileConfigurationManager.ts
https://github.com/microsoft/vscode/pull/133920
> feat: add jsxAttributeCompletionStyle settings

- Readme.md
- package.json
- src/server/features/completionItemProvider.ts
- src/server/features/fileConfigurationManager.ts
`typescript.suggest.includeCompletionsWithClassMemberSnippets` https://github.com/microsoft/vscode/pull/136045
> feat: includeCompletionsWithClassMemberSnippets

- src/server/features/folding.ts
Without this PR, the server will join the two ranges Like:
```javascript
if (true) {
// foo
} else if (false) {
// bar
}
```
> fix(folding): don't join folding range

- package.json
- src/server/features/linkedEditing.ts
- src/server/languageProvider.ts
- src/server/protocol.d.ts
- src/server/typescriptService.ts
- src/server/utils/api.ts
- yarn.lock
closes #423
Needs TypeScript 5.1.0
> feat: linkedEditing support

- package.json
- src/server/features/rename.ts
- src/server/languageProvider.ts
`typescript.preferences.renameMatchingJsxTags`
Needs https://github.com/neoclide/coc-tsserver/pull/427
> feat(rename): renaming of matching jsx tags

- package.json
- src/server/features/refactor.ts
- src/server/typescriptService.ts
- yarn.lock
https://github.com/neoclide/coc-tsserver/assets/345274/85941c28-c5f8-419f-96f3-074184b0b90f
> feat(refactor): move to file refactoring

- Readme.md
- package.json
- src/server/features/definitionProvider.ts
Closes https://github.com/neoclide/coc-tsserver/issues/449
> feat: add tsserver.preferGoToSourceDefinition
