neoclide/coc-tsserver

- src/server/utils/languageModeIds.ts
The change in https://github.com/neoclide/coc-tsserver/commit/c5c1630d8533136e20bfdc72d1846c4ef87a0c9e broke the autocompletion for `javascript.jsx` filetypes.
This PR adds it back while reserving the recently added `javascriptreact` filetype.
> Add back javascript.jsx to the languageIds

- src/server/typescriptServiceClient.ts
I think workspace.cwd should become workspace.root, this fixes the tsserver behaviour in my projects (where I use paths, etc in my tsconfig.json), without this the getProjectRootPath method returns the 'source file' path .
Please correct me if I am wrong, I am still new to the project (and never used visual studio) , so this took me some hours to figure out ;)
> bug fix: workspace.cwd -> workspace.root in getProjectRootPath()

- package.json
Hi,
Very minor thing, but just noticed that the "auto" option was missing in importModuleSpecifier
> Add missing option "auto" to importModuleSpecifier

- Readme.md
This PR removes an unsupported option: `orgnizeImportOnSave`. There was a type (missing `a`) and there aren't any similar options as far as I can see. Let me know if I can make this proposal better :)
Thanks for the project it is very useful 🙏
> doc(Readme): remove unsupported option

- src/server/typescriptServiceClient.ts
The `coc-tsserver` status bar item is not disposed of when disabling/toggling the extension in `coc.nvim`. This PR ensures the status bar item is removed so the duplication situation above does not occur.
> Dispose of status bar item when disabling tsserver

- src/server/utils/versionProvider.ts
this commit changes the `tsserver.js` resolution logic to use an absolute path rather than a relative one.
previously, if a user wanted to use a `tsserver.js` that was local to a project but didn't live in
`node_modules` (which would be automatically resolved by default), the `tsserver.tsdk` needed to be hardcoded to an absolute path. this required the user to modify `coc-settings.json` each time they wished to switch projects. by resolving to an absolute path, a user can now set the value to a relative path which will resolve correctly per project.
this change facilitates simplified usage of [Yarn v2's PnP feature](https://yarnpkg.github.io/berry/features/pnp), which [can generate](https://yarnpkg.github.io/berry/advanced/pnpify/) a project-specific `tsserver.js` to enable correct IDE …
> resolve `tsserver.js` via an absolute path

- src/server/features/fileConfigurationManager.ts
- src/server/features/rename.ts
Set 'providePrefixAndSuffixTextForRename' to true, as default in VSCode.
append "prefixText"  and "suffixText" if returned by tsserver 
Closes https://github.com/neoclide/coc-tsserver/issues/85
> fix rename feature

- package.json
- yarn.lock
- Update typescript to version 3.7 to support optional chaining etc: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html
- Update dependencies in general
I am using this locally without any issues
> Update dependencies (typescript 3.7)

- Readme.md
TSLint has been [deprecated](https://github.com/palantir/tslint/issues/4534).  Should put `eslint` first to direct users there.
> Deprecate TSLint

- Readme.md
- package.json
- src/server/typescriptServiceClient.ts
- src/server/utils/configuration.ts
When working with a huge project tsserver runs out of memory, so we need a way to configure memory limits for tsserver via coc-tsserver configuration. This is a direct port of VSCode change: https://github.com/microsoft/vscode/pull/82630/files/f22cde58663ba28d10ba43861a736b3c92f0a12b
> Add setting to configure the max memory for tsserver

- src/server/utils/versionProvider.ts
Pnpify SDKs are not located in `.vscode/pnpify` anymore. It's in `.yarn/sdks` instead. Adding it to `MODULE_FOLDERS`.
Without this patch, coc-tsserver works only when vim's CWD is exactly same with `.vim` directories location. For example, if you execute vim in the child directory, coc-tsserver does not work, which is not desirable.
- https://github.com/yarnpkg/berry/pull/1446: `.vscode/pnpify` &rarr; `.yarn/pnpify`
- https://github.com/yarnpkg/berry/pull/1481: `.yarn/pnpify` &rarr; `.yarn/sdks`
- https://github.com/neoclide/coc-tsserver/commit/52f625c453d36896252f2ab1818ff8c950222c7a#diff-5638766bbef81a3af0ffe200b24627e9
- https://github.com/neoclide/coc-tsserver/issues/166
> Support the new path of Yarn v2 pnpify SDK

- Readme.md
I fixed the default value of `importModuleSpecifierEnding` from `true` to `"auto"` on Readme.md.
> Fix default value of `importModuleSpecifierEnding` on Readme.md

- Readme.md
The README is not clear on this.
Go to definition does not work in typescript node_modules
ctags https://github.com/jb55/typescript-ctags is not a great alternative as it does not work well with ES6
Including the link to https://github.com/microsoft/TypeScript/issues/37777 has two benefits:
- will drive traffic to that issue and hopefully microsoft will solve it
- will help user find a workaround
tested on TypeScript 4.0.3
> README - Add info about typescript issue 37777

- src/server/features/completionItemProvider.ts
- src/server/utils/completionItem.ts
close #293
cc @chemzqm, tsserver returns `tsEntry.data` can be used in `resolveCompletionItem`, we can save it in `completionItem.data` to use.
> fix: save tsEntry.data for resolveCompletionItem

- Readme.md
This pull request updates the command needs to configure coc-tsserver using yarn 2+
I've tried following the documentation to use coc-tsserver with yarn 3.1.0 by running
```sh
yarn dlx @yarnpkg/pnpify --sdk vim
```
But I've got the following response on the terminal
```sh
$ yarn dlx @yarnpkg/pnpify --sdk vim
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 7s 504ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ tunnel@npm:0.0.6 can't be found in the cache and will be fetched fr
➤ YN0013: │ typanion@npm:3.3.2 can't be found in the cache and will be fetched 
➤ YN0013: │ which@npm:2.0.2 can't be found in the cache and will be fetched fro
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched fr
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched f
➤ …
```
> docs: update yarn configuration

- Readme.md
- package.json
- src/server/utils/configuration.ts
Closes #316
Automatic type acquisition is currently horribly flawed in that it does not check that it installs a correct or matching version of the types for the module in use. If the user has no guarantee that the types package installed at least is _supposed_ to match the version of the module they're using, this can be problematic if not dangerous.
For example, as mentioned in #316, I'm running Node v14, yet given types for Node built-ins that only exist v15+. While this creates a poor editor experience, as you cannot actually trust that you are returned correct warnings/errors, this gets dangerous in crypto and validation areas. If you're running v1 of a library while @types has a v2, **you will not get the definitions or descriptions to match what version you're using**. Depending on …
> refactor: Disables type acquisition by default

- Readme.md
- src/index.ts
- src/server/organizeImports.ts
add `source.sortImports` codeAction that used in `editor.action.sourceAction`, coc.nvim can add this too.
- `tsserver.organizeImports` will import/remove and sort the imports
- `tsserver.sortImports` does sorting only
> feat: add tsserver.sortImports

- package.json
- src/server/features/fileConfigurationManager.ts
- src/server/features/inlayHints.ts
- src/server/languageProvider.ts
- src/server/typescriptService.ts
- src/server/utils/api.ts
related #300, all inlay hints configurations are disabled by default.
@chemzqm the current implementation will fetch and render full document because TS can only return inlay hints for full. I've used for months, didn't come across performance issues.
> feat: inlay hints support

- Readme.md
The default for these two are actually `shortest`.
[typescript](https://github.com/neoclide/coc-tsserver/blob/master/package.json#L304)
[javascript](https://github.com/neoclide/coc-tsserver/blob/master/package.json#L565)
> correct README importModuleSpecifier configuration examples

- src/server/typescriptServiceClient.ts
with the neovim change to expect zipfile:// urls instead of zipfile: urls, the current toResource implementation does not work with going to definitions inside of zipfiles.
As far as I can tell, attempting to change the tsserver sdk in https://github.com/cometkim/berry/blob/master/.yarn/sdks/typescript/lib/tsserver.js#L80 will not work, as the use of `Uri` compresses any form of `zipfile:///` into `zipfile:/`, requiring a bypass of the current logic.
> toResource should return zipfile:// urls when using go to definition with yarn PnP

- package.json
- src/server/commands.ts
- src/server/index.ts
- src/server/utils/api.ts
`tsserver.goToSourceDefinition`, close #383
> feat(commands): Go to Source Definition

- src/server/features/updatePathOnRename.ts
Closes #446 by increasing the delay value to `1000`. Hopefully this is big enough to work on slower machines and short enough not to get noticed by end-users.
> Fix(refactor): File rename does not update import paths

- src/server/features/fileConfigurationManager.ts
Closes https://github.com/neoclide/coc-tsserver/issues/453
> feat: pass through `typescript.unstable` to tsserver
